export const API_ENDPOINT = process.env.REACT_APP_API_ENDPOINT
export const USER_STORAGE_KEY = '_u'
export const CONVERSATION_DB_NAME = 'conversations'
export const CLOUD_NAME_CLOUDINARY = process.env.REACT_APP_CLOUD_NAME_CLOUDINARY as string
export const UPLOAD_PRESET_CLOUDINARY = process.env.REACT_APP_UPLOAD_PRESET_CLOUDINARY as string
export const CLOUDINARY_URL = process.env.REACT_APP_CLOUDINARY_URL as string
export const SECRET_KEY_ENCRYPT = process.env.REACT_APP_SECRET_KEY_ENCRYPT as string
export const START_TRACKING_WORKER_HANDLER_CODE = 'START'
export const MAX_REQUEST_PER_MIN_WARN = 40
